#!/bin/sh
op=$( echo -e "󰐥 Poweroff\n󰜉 Reboot\n󰤄 Suspend\n󰈆 Logout" | wofi --width 10% --height 18% -i --dmenu | awk '{print tolower($2)}' )

case $op in 
        poweroff)
                ;&
        reboot)
                ;&
        suspend)
                systemctl $op
                ;;
        logout)
		hyprctl dispatch exit
                ;;
esac
