{
  imports = [
    ./alpha.nix
    ./autoclose.nix
    ./barbar.nix
    ./cmp.nix
    ./colorizer.nix
    ./comment.nix
    ./dap.nix
    ./lsp.nix
    ./lualine.nix
    ./luasnip.nix
    ./mini.nix
    ./neotree.nix
    ./nix.nix
    ./telescope.nix
    ./toggleterm.nix
    ./transparent.nix
  ];
}
