vim.g.mapleader = " "
vim.g.maplocalleader = " "

local o = vim.opt

o.clipboard = "unnamedplus"
o.completeopt = "menu,menuone"
o.expandtab = true
o.ignorecase = true
o.mouse = ""
o.number = true
o.relativenumber = true
o.shiftwidth = 2
o.showmatch = true
o.signcolumn = "yes"
o.smartcase = true
o.smartindent = true
o.softtabstop = 2
o.splitbelow = true
o.splitright = true
o.swapfile = false
o.tabstop = 2
o.termguicolors = true
o.timeoutlen = 500
o.updatetime = 300
o.wrap = false
o.scrolloff = 12
o.cursorline = false
o.guicursor = "n-i-v-ve-c-ci-sm:block,r-cr-o:hor20"
